# encoding:utf-8
import copy
import queue
import re
import time
import requests
from lxml import etree
from queue import Queue
import threading
from urllib.parse import urlparse
from tool.get_min_gan_word import get_mingan_word

#检测是否是中文
def check_contain_chinese1(check_str):
    for ch in check_str:
        if u'\u4e00' <= ch <= u'\u9fff':
            return '中文'

    return '其他'

#检测是否是中文
def check_contain_chinese(url_list):
    for url in url_list:
       if '.' not in url:
           return True
    return False


words = get_mingan_word()
proxy_queue = queue.Queue()
def get_proxy():
    while True:
        if proxy_queue.qsize()> 100:
            time.sleep(2)
            continue
        url = 'http://222.186.42.15:7772/SML.aspx?action=GetIPAPI&OrderNumber=a2b676c40f8428c7de191c831cbcda44&poolIndex=1676099678&Split=&Address=&Whitelist=&isp=&qty=20'
        try:
            r = requests.get(url, timeout=3)
            if '尝试修改提取筛选参数' in r.text or '用户异常' in r.text:
                print('尝试修改提取筛选参数')
                time.sleep(20)
                continue
            ip_list = r.text.split('\r\n')
            for ip in ip_list:
                if ip.strip() == '': continue
                proxy_queue.put(ip)
        except Exception as e:
            time.sleep(1)
            print(e)
            continue

threading.Thread(target=get_proxy).start()




class BaiDu():
    def __init__(self,baidu_record=[0,0],kuaizhao_time='',lang_chinese='',min_gan_word=''):


        self.proxies = self.get_proxy()
        self.s = requests.session()
        self.baidu_record = baidu_record
        self.baidu_record_min = int(baidu_record[0])
        self.baidu_record_max = int(baidu_record[1])
        self.baidu_record_max = 999999999 if self.baidu_record_max == 0 else self.baidu_record_max
        self.kuaizhao_time = kuaizhao_time
        self.lang_chinese = lang_chinese
        self.min_gan_word = min_gan_word

    def get_proxy(self):
        try:
            ip = proxy_queue.get()
            proxies = {
                'http': f'http://{ip}',
                'https': f'http://{ip}'
            }
            self.proxies = proxies
            return proxies
        except Exception as e:
            time.sleep(2)
            return None


    # 查找关键词
    def find_word(self, seg_list):
        global words
        """
        # 匹配敏感侧
        :param seg_list:
        :return:
        """
        title_sensi = ""

        for w in words:
            if str(w) in seg_list:
                title_sensi += w + "|"
        if title_sensi != "":
            return title_sensi
        else:
            return "无结果"


    def requests_handler(self, url1,is_yz=False):
        url = f"https://www.baidu.com/s?f=8&rsv_bp=1&wd=site%3A{url1}"

        headers = {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
            'Accept-Language': 'zh-CN,zh;q=0.9',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
            'Host': 'www.baidu.com',
            'Pragma': 'no-cache',
            'Referer': 'https://www.baidu.com/',
            'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
            'Sec-Fetch-Dest': 'document',
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'same-origin',
            'Sec-Fetch-User': '?1',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36',
            'Cookie': 'BIDUPSID=7E8FF5B8B6A04F730D326E096D797311; PSTM=1631605740; BAIDUID=7E8FF5B8B6A04F73916DB66CF6DA889A:FG=1; __yjs_duid=1_ac59271c36da10cdc87f4dc99a62b19b1631605755856; BD_UPN=12314753; BDUSS=HRGaEZLblB1QVN-cW9zUS1ER0o0SFNmOWo3Z3lnS2RWc1luYVpRNk51SndwSWhpRVFBQUFBJCQAAAAAAAAAAAEAAAAAJZjRYmF5dWxpYW4xMDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAXYWJwF2FiV; BDUSS_BFESS=HRGaEZLblB1QVN-cW9zUS1ER0o0SFNmOWo3Z3lnS2RWc1luYVpRNk51SndwSWhpRVFBQUFBJCQAAAAAAAAAAAEAAAAAJZjRYmF5dWxpYW4xMDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAXYWJwF2FiV; H_WISE_SIDS=107314_110085_114550_127969_174441_179350_180636_184716_188746_189755_190623_191527_194085_194519_194530_196426_197241_197711_197956_199574_201193_203517_206906_207236_207574_207729_208608_208721_209455_209568_210091_210306_210440_210470_210642_210664_210757_210851_211288_211435_211558_211732_212416_212699_212778_212797_213031_213060_213094_213125_213353_213416_213596_213645_214005_214025_214115_214129_214138_214142_214396_214535_214655_214793_214883_215175_215280_215457_215484_215727_215806_215829_215859_216049; BDSFRCVID_BFESS=3WCOJeC62rTEVBJDlYXsMFIMlmPlqOOTH6aoTq4RcGLzFvWtAe3mEG0P5x8g0KuM3ulxogKKLmOTHpKF_2uxOjjg8UtVJeC6EG0Ptf8g0f5; H_BDCLCKID_SF_BFESS=tR4joID5tC-3fP36q4bs5t_HbUR0-I62aKDs-PDMBhcqEIL4jhjkM5-pQMcH0t33Bn7dhIojthjzHxbSj4QoQbt_jb_j35ci5CoMaKjYah5nhMJEb67JDMP0qfbe3hoy523i2n6vQpn2OpQ3DRoWXPIqbN7P-p5Z5mAqKl0MLPbtbb0xb6_0j5OBDG_eJ60s-C5KWJnaHt3qjRTphR6s-t6H-UnLq5oaX2OZ0l8KttK2eK3mXUOCXn8WM-keQhvMtjueXDOmWIQthn6wQJ6kjp5-DMt80JTz-nR4KKJxLlCWeIJo5fFhKxuehUJiBM7LBan7QpvIXKohJh7FM4tW3J0ZyxomtfQxtNRJ0DnjtnLhbC89jj-MDT5LepJq-J-XM6vH0RcXHJO_bIO5LUnkbfJBDl5n0l5GWenQhxnbBlQz8JRz0-vaXU47yajK2h3DJNr2KhRL3tQRfhjNDPcpQT8rjqAOK5OibmDeLRRyab3vOpRzXpO1KMPzBN5thURB2DkO-4bCWJ5TMl5jDh3Mb6ksDMDtqtJHKbDeoKLMfU5; BDORZ=B490B5EBF6F3CD402E515D22BCDA1598; BAIDUID_BFESS=7E8FF5B8B6A04F73916DB66CF6DA889A:FG=1; BA_HECTOR=85a12lah242ka58l802mdcnb1hd74nc17; ZFY=ba75SbVoKLf:AJxKUdLtbSEwnx:BPnQN7SAJHpxFCIMZk:C; BD_HOME=1; H_PS_PSSID=36558_36625_36820_36454_36413_36611_36692_36165_36816_36775_36745_36762_36771_36764_26350; delPer=0; BD_CK_SAM=1; PSINO=6; H_PS_645EC=a3c72gk8irtDfWDIrQiWofEHgqpQmJfOoP7TmNwXu7uwiQR6MINMvLZ45eA; channel=baidusearch; baikeVisitId=6ac61418-a9ce-47a5-ac60-b1c7abd4b0b6'
            # 'Cookie': 'BAIDUID=FE5D3C7F6CAAF5A80701894E937B66C2:FG=1; BIDUPSID=B2CE0F7F4FACBD5E54D7A2EF967F7D5D; BD_UPN=12314753; H_PS_PSSID=36543_37352_36885_34813_37486_37402_37396_36569_36786_37071_26350_37344_37372; BDORZ=B490B5EBF6F3CD402E515D22BCDA1598; BAIDUID_BFESS=FE5D3C7F6CAAF5A80701894E937B66C2:FG=1; BD_HOME=1; delPer=0; BA_HECTOR=218l2k8hal0k012h802lfnpa1hj7acd1a; ZFY=cMpoHD8KA4cRAxz88vZGKrU0Pz:AA6UjS9TTTXS:AyI6Y:C; BD_CK_SAM=1; B64_BOT=1; COOKIE_SESSION=159677_3_8_6_5_13_1_0_3_7_0_1_159742_89_3_0_1664335776_1664005747_1664335773%7C9%2333_4_1664005672%7C2; PSINO=7; H_PS_645EC=82b5rVoBLL0BGMQjI4j2q9mrsheDDXZ3dHodpCt8T1im4lzVAVR3clFJuKE; BDSVRTM=0; WWW_ST=1664345254413'
        }

        try:
            if is_yz == False:
                response = requests.get(url,headers=headers,timeout=3)
            else:
                h = copy.deepcopy(headers)
                del h['Cookie']
                response = requests.get(url, headers=headers, proxies=self.proxies, timeout=10)

            response.encoding = 'utf-8'
            if '百度安全验证' in response.text:
                self.get_proxy()
                print(f'出现百度安全验证 更换代理 {self.proxies}')
                return self.requests_handler(url1,True)
            elif response.text.strip()=='':
                return None
            elif '<div id="__status">' in response.text:
                return None
            return response
        except Exception as e:
            # self.get_proxy()
            # log.logger.error(f'更换代理 {e}')
            # return self.requests_handler(url1)
            return None

    def get_domain_url(self,baidu_url,count=0):
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36',
            }
            # r = requests.get(baidu_url,headers=headers,verify=False)
            r = requests.get(baidu_url, headers=headers, verify=False, allow_redirects=False)
            url = r.headers._store['location'][1]

            return url
        except Exception as e:
            if count < 5:
                return self.get_domain_url(baidu_url,count+1)
            return ''

    def check_baidu(self,r,domain):
        '''
        :param r: json对象
        :param domain: response 响应对象
        :return: 返回是否符合要求 是true   否 返回失败信息
        '''
        if r == None:
            return '请求失败'
        domain = domain.lower()
        html = etree.HTML(r['html'])

        if html == None:
            return '请求失败'

        # 数据量
        h3_list = html.xpath('//div[@class="result c-container xpath-log new-pmd"]')

        record_count = len(h3_list)
        if record_count >= 10:
            record_count = int(r['sl'])
        # 判断收录数 最小值小于 实际过滤
        if self.baidu_record_min > int(record_count) or int(record_count) > self.baidu_record_max:
            return f'百度 收录数不符合要求: 收录数为{record_count}'


        #判断是否有敏感词
        if self.min_gan_word == '1':
            title_list = []
            for d in h3_list:
                try:
                    title_list.append(str(d.xpath('.//h3[@class="c-title t t tts-title"]//a/text()')[0]).replace(domain," ").replace(","," ").replace("\n", ""))
                except Exception as error:
                    continue
            if title_list == []: return '百度 没有找到标题 无法判断是否包含敏感词'
            for t in title_list:
               for w in words:
                   if w in t:
                       return f'百度 包含敏感词：{w}'


        #获取全部url
        url_list= []
        #显示的url
        show_url_list = []
        for d in h3_list:
            try:
                url = self.get_domain_url(d.xpath('.//h3[@class="c-title t t tts-title"]//a/@href')[0])
                if domain in url.lower():
                    source_url = d.xpath('.//span[@class="c-color-gray"]//text()')[0]
                    url_list.append(url)
                    show_url_list.append(source_url)
            except Exception as error:
                pass

        #判断url中是否包含中文
        if self.lang_chinese == '1':
            # if check_contain_chinese(''.join(url_list)) != '中文':
            if check_contain_chinese(show_url_list) == False:
                return '百度 url中没有中文'


        # 判断url结构   1首页     2泛   3内页 0不判断
        is_guo = False
        if self.kuaizhao_time == '0':
            return True
        elif self.kuaizhao_time == '1':
            for url in url_list:
                host = urlparse(url).hostname
                if host == None:
                    continue
                if (host.split('.')[0] == 'www' or host.count('.') == 1 )and (len(urlparse(url).path) <= 1):
                    is_guo =True
                    break

            if is_guo == False:
                return '百度 首页判断未通过'

        elif self.kuaizhao_time == '2':
            for url in url_list:
                domain_1 = urlparse(url).hostname
                if domain_1 == None:
                    continue
                if domain_1.count('.') >= 2 and domain_1.split('.')[0] != 'www' and 'm.' not in domain_1:
                    is_guo = True
                    break

            if is_guo == False:
                return '百度 泛判断未通过'

        elif self.kuaizhao_time == '3':
            for url in url_list:
                domain = urlparse(url)
                if domain.path != '/' and domain.path != '':
                    is_guo = True
            if is_guo == False:
                return '百度 内页判断未通过'

        return True

    def get_info(self,domain):
        r = self.requests_handler(domain)
        if r == None:
            return None
        html = etree.HTML(r.text)
        # 数据量
        h3_list = html.xpath('//div[@class="result c-container xpath-log new-pmd"]')
        try:
            record_count = int(re.findall('找到相关结果数约(.*?)个',r.text)[0].replace(',',''))
        except Exception as error:
            record_count = 0
        if html == None:
            return None
        try:
            html = etree.tostring(html.xpath('//div[@id="container"]')[0],encoding='utf-8')
            data = {'sl':record_count,'html':html.decode()}
            return data
        except Exception :
            return None
if __name__ == '__main__':
    ls = ["0431auto.cn",
"wncet.cn",
"bjmsaj.cn",
"cxz123.net",
"cool-may.com",
"jsbomingxing.com",
"fjfzwl.com",
"eahchanie.top",
"changyuanclub.com",
"szlgw.cn",
"fbdby.cn",
"yayaqq.cn",
"gdxinchao.cn",
"aglongyu.com",
"bdksxvb.cn",
"dstx365.com",
"szgtg.cn",
"687kj.com",
"cnlyszy.com",
"kingdoc.cn",
"norcee.com",
"muvn.cn",
"mssqztdzw.com",
"szhtwy.cn",
"jinseshulin.cn",
"tm871.cn",
"zhonghuahunqing.com",
"qingyi888.com",
"tdfzc.com",
"myxumu.com.cn",
"htymqwg.cn",
"rhjwmkd.cn",
"iajlmyw.cn",
"ktllnfb.cn",
"lgzsbkg.cn",
"cdlnd.cn",
"anjuc.cn",
"hyplnlp.cn",
"huiruiguanye.cn",
"d9nyx.cn",
"ynuhvrm.cn",
"newenglandgreenfunerals.com",
"re-monter.com",
"duritoedizioni.com",
"nailfetishpa.com",
"pianyiwg.com",
"odessa555.com",
"maisondesplans.com",
"bbbeodi.cn",
"yinotok.cn",
"emmaruna.com",
"thrillerlaserworld.com",
"zqb6u.cn",
"znnlisans.com",
"unslan.com",
"munhorgil.com",
"ln-n.com",
"zonabarca.com",
"woj2w.cn",
"lumepil.com",
"454ua.cn",
"gunerbilisim.com",
"777die.com",
"sxm3p.cn",
"87bbg.cn",
"quanpingshangmao2.cn",
"7g54m.cn",
"hgbim.cn",
"daag6.cn",
"qgpc7.cn",
"0rbq1.cn",
"0lb9s.cn",
"3dmvl.cn",
"41t6w.cn",
"8vdb3.cn",
"netsysadm.com",
"b71bd.cn",
"3n7ia.cn",
"alcicam.com",
"kainprac.com",
"5wvrz.cn",
"napteker.com",
"630u0.cn",
"gyl1n.cn",
"art-dimas.com",
"nj8s6.cn",
"fiyde.cn",
"crimea-as.com",
"eurorey.com",
"243szy.cn",
"h9rfq.cn",
"balonpes.com",
"madaloud.com",
"juliesolo.com",
"admknives.com",
"0jf5q.cn",
"66psb.cn",
"ztl92.cn",
"tehuizuhao.com",
"maysfilm.com",
"may-karl.com",
"jxfjm.com",
"ishiyuiya.com",
"pm-blogs.com",
"3d1m6.cn",
"mwasalate.com",
"63478898.com",
"y6371qw.cn",
"fvv7d.cn",
"db0nb.cn",
"ik5h26.cn",
"bp5bh.cn",
"v5zec.cn",
"m2r2w.cn",
"p30vel.com",
"yooaskme.com",
"u3rc579y.cn",
"6s212.cn",
"17m08.cn",
"2af9gjyl.cn",
"artier.net",
"ghazal-co.com",
"jzyekks.cn",
"husuke.com",
"tvhostguy.com",
"djr154.cn",
"3z7osm.cn",
"q33qt.cn",
"wagz2.cn",
"pamzulauf.com",
"304hkv.cn",
"1cqyxk.cn",
"5xjls.cn",
"jrrjn.com",
"3xu6wy.cn",
"gxm6bez5.cn",
"277aqs.cn",
"hnsjgd.com",
"45cy21w.cn",
"159lsh.cn",
"snbrfgy.cn",
"omta9sv.cn",
"bradleyjconomy.com",
"fci596t.cn",
"624umv.cn",
"49ymdk8.cn",
"ympod8.cn",
"rqw451.cn",
"aib3wz2.cn",
"48zsw9.cn",
"0b2wx.cn",
"czfcsc.com",
"17fkxrs9.cn",
"ftazn.com",
"k8c58a24.cn",
"eau968.cn",
"drgertzman.com",
"878smw.cn",
"f6u38t.cn",
"349azk.cn",
"509fvp.cn",
"ju3w691.cn",
"8q16ar.cn",
"bg4hu.cn",
"astne.cn",
"ydp881.cn",
"p94tu6.cn",
"uvt657.cn",
"zyex8.cn",
"nys3wv.cn",
"dzi426.cn",
"853ofk.cn",
"oj6sd6t.cn",
"b51742.cn",
"gucf3.cn",
"8yp62.cn",
"ewl933.cn",
"1td1ohz3.cn",
"551cdh.cn",
"116jks.cn",
"32ibqd.cn",
"zhqkmvy.cn",
"911ep.com.cn",
"sstateam.com",
"kdosn.com",
"syds166.cn",
"asgeek.cn",
"ianhui.com.cn",
"4cmnb3zv.cn",
"3oy216.cn",
"yzhfdz.com",
"dbpam.cn",
"miajoya.com",
"76303.cn",
"ujsblxs.com",
"xywangx.com",
"alandaleinsurance.com",
"gxbxlh.com",
"boursex.com",
"bigdippertours.com",
"xuejsw.com",
"nmmgsw.com",
"jptpay.com",
"jsfores.com",
"haoquan86.com",
"slothbars.com",
"91sida.com",
"sdrtjl.com",
"doouxiang.com",
"thermo-chromic.com",
"hchcgs.com",
"jssyktsb.com",
"sznjst.com",
"yi869.cn",
"grtsea.com",
"jhkerui.com",
"5555wang.com",
"yuyafeng.com",
"neatglobe.com",
"svesv.com",
"jhbzb.com",
"zc-qj.com",
"hahag.cn",
"zgjf123.com",
"eyijiao.net.cn",
"shuwy.com",
"yxsmb177.com",
"iv78.com",
"sp221.cn",
"gtyy6588.com",
"myn120.com",
"5879game.com",
"hbxiangsuzhipin.com",
"me961.cn",
"zzjiefa.com",
"czjtime.com",
"nescast.com",
"meitianyidian.com",
"chexiuma.com",
"96zhz.com",
"kuang-lian.com",
"jp971.cn",
"xinyangyimei.com",
"bananarj.com",
"ju123q.cn",
"maitianmeishi.cn",
"ganzhehealth.cn",
"dx-blog.com",
"hbxfgd888.com",
"lst163.com",
"zhendezhuxian.com",
"jybdyzp.com",
"baiyetongbao.cn",
"ltz-zxyey.com",
"douzhewan.com",
"zghuixiang.com",
"lh876.cn",
"sh-ymsy.com",
"zuitepai.com",
"wulianliuliangka.com",
"jsbaidaly.com",
"51wlsj.com",
"tingyiwl.com",
"bigman100.com",
"683fi.com",
"aizhyq.cn",
"joracon.cn",
"ajcfaz.cn",
"dlposo.cn",
"yuyangxk.com",
"zswy24.com",
"sr987.cn",
"nrhw.com.cn",
"eeetxue.cn",
"eduilian.net",
"qgcxzsfw.com",
"caron-cr.com",
"bjzcwxjj.com",
"yytthh.com",
"hcjsfw.cn",
"alideli.cn",
"zaymjz.cn",
"skffmcj.cn",
"fcqydl.com",
"itlinnan.com",
"czghp.cn",
"scssg.cn",
"biccc.org.cn",
"laobif.cn",
"xuyingtc.com",
"mv982.cn",
"rlbhvn.cn",
"duumjbv.cn",
"hongkunlaowu.com",
"duotianjj.com",
"hpto.cc",
"crxssl.cn",
"uymsvhw.cn",
"tpckj.cn",
"ntt956.com",
"jixjuwd.cn",
"nrlhbh.cn",
"mjqjvai.cn",
"leica-guomao.cn",
"plbcrkp.cn",
"deokana.com",
"qi259.cn",
"moyangs.com",
"cyrilsimonnot.com",
"wsxianjiao.com",
"hebeizhiyou.com",
"hnxyjiaju.com",
"miaowang263.com",
"hspx.com.cn",
"vo388.cn",
"haazar.com",
"bmciudadparla.com",
"dd676.cn",
"ivanossandpoint.com",
"gulhod.com",
"notdepositcasino.com",
"scszjt.com",
"taoimage.cn",
"webmastersltda.com",
"zhongmeikang.com",
"hilomoped.com",
"rydeflightsupport.com",
"ya539.cn",
"nastyhearts.com",
"ow815.cn",
"fastoffroad.com",
"banshigang.com",
"zhixingxinxi.com",
"pshus.cn",
"pdqbxzp.cn",
"jsbeide.cn",
"aixin011.com",
"yz785.cn",
"persiancarpets.com.cn",
"qianbaige.cn",
"ilovemalita.com",
"dingfei029.com",
"pshusa.cn",
"chinabestfoods.com",
"tgcz.com.cn",
"indiakitchenca.com",
"so9art.com",
"jdsiyuan.com",
"yiqingcaokeji.com",
"zhidingjiaoyu.com",
"pshusw.cn",
"ci511.cn",
"zw571.cn",
"laterreletemps.com",
"thepfeils.com",
"esthetique-a-domicile-marseille.com",
"xnyb.com.cn",
"xfjjdd.cn",
"ouzhoubeiickyp.com",
"enzao.cn",
"masgushi.com",
"wxscfy.com",
"ih192.cn",
"mootaab.com",
"solobagus.com",
"endopmedical.com",
"montesonline.com",
"onlinecasinoluckguide.com",
"nthsyzs.com",
"xykyczj.com",
"baziq.cn",
"greenlandhhht.com",
"zhoucunxinchang.com",
"weijijin.com.cn",
"lcpgsc.cn",
"maxkazanc.com",
"dlddcy.com",
"brend-lux.com",
"chinavideocity.com",
"china2z.com",
"atexp.com",
"viewtubr.com",
"leithforpa.com",
"jordanlusk.com",
"xk1k.com",
"lbaplmc.com",
"eh256.cn",
"nonaimcorrib.com",
"pcpn.cc",
"8vista.cn",
"4k-ol.com",
"tljmultimedia.com",
"yourenbang.vip",
"1stindependentleasing.com",
"convert2silver.com",
"fuleyun.cn",
"itripitrip.com",
"jnmh.com.cn",
"yafengshang.com",
"zyyjjt.com",
"bttdapp.cn",
"kibou.cn",
"dfmold168.cn",
"vnzbnjx.cn",
"hnxing.com",
"gfqtcazv.cn",
"koth.cn",
"jiayisport.cn",
"veansan3d.com",
"stznjy.com",
"lehuimall.cn",
"fast-painrelief.cn",
"bjjsdd.cn",
"jinfan1987.cn",
"sdwzdy.com.cn",
"0898yuebing.com",
"debseitz.com",
"ght24.com",
"zglmxh.org.cn",
"fayeillustration.com",
"julangedu.cn",
"iredshift.cn",
"hsdamen.cn",
"microfinance-expo.com",
"zjnuomi.com",
"czujjl.com",
"sqbfl.com",
"pcbaled.com",
"aitaizi.com",
"albergocentralepeio.com",
"9dcloud.cn",
"handballclub.net",
"springbaycounseling.com",
"everydayindiancooking.com",
"aaaquickdry.com",
"thebeachactivities.com",
"stuartbeachmusic.com",
"themorningowls.com",
"chshorses.com",
"ellosingapore.com",
"mobis3.com",
"ecopurewaterproducts.com",
"zhitaojiaju.com",
"bag-machinery.com",
"sanlikeji.com.cn",
"rickmasonphoto.com",
"fuxingjk.com",
"asesoriaofelianieto87madrid.com",
"bjgaoge.com",
"magashoes.com",
"madames-port.com",
"sdkcgt.cn",
"seyo-tw.com",
"llxzr.com",
"dds9666.com",
"qnqe.cn",
"liteer.cn",
"binfenghb.com",
"onlydopestuffvip.com",
"hongjiayao.com",
"you6you7.com",
"jibaixin.cn",
"ysmould.com.cn",
"a29w.cn",
"khtmy.com",
"dgdk998.com",
"sdhzhy.cn",
"baishiyun.cn",
"yeshun888.com",
"0739go.com",
"magnanimal.com",
"whbstgd.com",
"jzinv.com",
"zhusuji18.cn",
"lscyms.cn",
"powerway-bj.cn",
"aoshiam.cn",
"9097tv.com",
"tianmaocoupon.com",
"zjgcdw.cn",
"xczxzs.com",
"zhpicc.com",
"gdjxlg.cn",
"shintamichiko.com",
"shtree.com",
"sudida.cn",
"yxyex.cn",
"kankanthailand.com",
"barcthailand.com",
"iguoli.cn",
"iinhq.com",
"retro-phonia.com",
"sjpl.net.cn",
"hqzz180.cn",
"62599.cn",
"sztob.com",
"salonchezmimi.com",
"koryunet.org",
"arxingteng15th.cn",
"roofing-contractors-gta.com",
"top20ukraine.com",
"nychinesecafemissouricity.com",
"hddxbj.com.cn",
"writelog.cn",
"tykly.cn",
"apnet21.com",
"83xd.com",
"mijingji.com",
"xyaft.com",
"jntlp1718.com",
"haichuangyunyou.com",
"hfhsks.cn",
"7733383.cn",
"jinliuyu.cn",
"szfhkq.cn",
"youdancard.cn",
"ngdynsworg.cn",
"e7pt.com",
"jnrso.com",
"fjb99.com",
"qhzylygs.com",
"drus.com.cn",
"58591666.com",
"gczmdj.com",
"cazinoha.com",
"gtsrfinance.com",
"sxjmky.cn",
"jingchenggongsi.com",
"dlth.com.cn",
"xinyuelai.cn",
"qiati.cn",
"manmango-home.com",
"xushide.cn",
"youyuangou.cn",
"fhglass.cn",
"arisoze.cn",
"xajingchun.cn",
"dope-tech.com",
"lsbskc.cn",
"diao-wan.com",
"baojialidingzhi.com",
"gsoftech.cn",
"xianghen.cn",
"oslanboli.com",
"nyajkl.com",
"bmc-ch.com",
"alabamahuntingtoday.com",
"canietionline.com",
"dalanproductions.com",
"dresstoimpressllc.com",
"a1mobilecomputer.com",
"collegedebtsolution.com",
"leganordbusto.com",
"thomasvillecs.com",
"castlecaninecreations.com",
"plussizeconnection.com",
"beadattitudesjewelry.com",
"inversiontablesdirect.com",
"karatecentertangsoodo.com",
"soundmindandbodyllc.com",
"americanbullriderstour.com",
"unlulerinboylari.com",
"demopublicanparty.com",
"industriegabriele.com",
"cmdconstructionltd.com",
"metrokirschrealestate.com",
"gspas2000.com",
"rumbacrazy.com",
"guanganbc.com",
"thedogprime.com",
"ninethreebeauty.com",
"chengrengaokao-edu.com",
"paulson-ranch.com",
"tampoiledanghotel.com",
"vidix-usa.com",
"armandacirio.com",
"namona-design.com",
"gobbosimone.com",
"lotrsketches.com",
"ronsmswalk.com",
"i-playsport.com",
"canlidizihd.com",
"amherstnaz.com",
"acker-immigration.com",
"gets-textile.com",
"simeonlazarov.com",
"aafastpitchcamps.com",
"sunnysideyarns.com",
"reddressball.com",
"kingsandkillers.com",
"anasacerdote.com",
"eventsbyelisa.com",
"labelofhope.com",
"lofficiel-india.com",
"trowbridgeart.com",
"rjyg11.cn",
"whfhxgs.cn",
"dhudsoncounseling.com",
"girlgamestoday.com",
"cunf.cn",
"reddytimes.com",
"yiyiwangke.com",
"cdqczp.com",
"pedoedu.com",
"niudanjia.com",
"sblzxlm.com",
"gxljw.com",
"yqshiyu.com",
"1527d.com",
"dgknhg.com",
"999friends.com",
"hongjiadoors.com",
"premiumunderpads.com",
"hotelcourchevel.com",
"teknowgroup.com",
"matthew6-34.com",
"ginsterscareers.com",
"karoserijaservis.com",
"robbiereynard.com",
"mydestroyer.com",
"ihuangrong.com",
"gojf8.com",
"xifengzui.com",
"172play.com",
"abroaduk.net",
"hbdbcf.com",
"xrdryp.com",
"daqingfuke.com",
"yoaprendoonline.com",
"63163.cn",
"vs658.cn",
"gx-ybcm.com",
"0577kayou.com",
"top20thailand.com",
"cambodiawindow.com",
"xunow.com",
"hnlcfm.com",
"gdaudio168.com",
"89cun.com",
"chinaykl.com",
"zjweuser.cn",
"bestkeye.com",
"jmtmuk.com",
"ytczpg.com",
"qpfy.cn",
"weishimai.com",
"tfefww.com",
"ennmqa.com",
"xjypba.com",
"ybuzvn.com",
"jinxiting.com",
"jydwyy.cn",
"jaroslawmorawski.com",
"qiyusizhuangshi.com",
"meitianbangzhu.com",
"extremecouponshere.com",
"7000minbak.com",
"pagecyclediet.com",
"domainscratch.com",
"ddmediainc.com",
"evehoggan.com",
"htmmdq.com",
"cd-dkw.com",
"dayujituan.cn",
"227792.com",
"topivr.com",
"wuqing365.com",
"dazhongtuiguang.com",
"yxjinben.com",
"sh-hospital.com",
"yuankangsw.com",
"huaxiaqizhi.com",
"tkmkl.cn",
"wanshangyundian.com",
"hbkuoquan.com",
"iovona.com",
"884793.cn",
"documentalfolk.com",
"xuelangfood.com",
"bleuesarl.com",
"dlbaiheng.cn",
"fuchuansxh.cn",
"jccc-jstec.cn",
"dbbnqmjh.cn",
"nanishitou.com",
"ngfjwzhs.com",
"fulinyuan888.com",
"tsstent.com",
"xhfskj.com",
"jiujingceshiyi.com",
"norskesexfilmer.net",
"yhddyj.com",
"lhgggs.cn",
"daierlangxiang.com",
"gps-log.com",
"skyenetmedia.com",
"mybareahop.com",
"agenbbm88.com",
"youchengt.com",
"eligflor.com",
"tongshengxuan.com",
"nhol-chn.com",
"sh-lixue.com",
"hnhtennis.com",
"gmanchina.com",
"hzyeye.com",
"saintgano.com",
"mucaoyuan.com",
"collectedhouse.com",
"szylmj.com",
"jiningtour.com",
"buguannixinbuxin.com",
"taipei-shop.com",
"chengjijx.com",
"evodecoration.com",
"vczhushou.cn",
"szxzx-ic.com",
"digitalcloudpress.com",
"d14yrkei.cn",
"karster.com",
"zushushuang.com",
"dianfuqipai.com",
"mxl02.xyz",
"hqzyfs.com.cn",
"hwy11.cn",
"brandking.cn",
"longxingshanglv.com",
"10000essay.com",
"ssfaye.com",
"gywcs1.com",
"asth-consulting.com",
"mamabeta.cn",
"smilesandsuch.com",
"bigtrav.com",
"parableslo.com",
"roosterbikes.com",
"craigalunsmith.com",
"sdtuomasi.cn",
"baotingfdc.com",
"darrylpetch.com",
"xnpk.cn",
"bsshclxs.com",
"vi271.cn",
"force1hosting.com",
"imaginaunllocon.com",
"xakyj.com.cn",
"varietylounge.com",
"puchuntang.com",
"nnncnc.com",
"ffzzzf.com",
"llfwjbba.com",
"llbztwsc.com",
"llbztwsa.com",
"llbztws.com",
"hhbztwsa.com",
"hhbztws.com",
"tradeshow-advertising.com",
"marshaburnett.com",
"woori31.com",
"shn-mipt.com",
"zpydimm.com",
"sdhssj.com",
"qsptw.com",
"zuowenfou.com",
"anchorway.com.cn",
"shuju365.com.cn",
"ww98.cn",
"eagg.cn",
"wangye-sheji.cn",
"wzwt.com.cn",
"youguoyoushipin.com",
"zkkfyy.com",
"yxfb.vip",
"brio-tattoo.com",
"ts-media.com.cn",
"senpushihua.com",
"maxihelpdesk.com",
"ep3.com.cn",
"sncrca.com",
"commentonhealth.com",
"dl-ultrair.com",
"supperwine.cn",
"ahqlmsy.com",
"idcpt.cn",
"jfjyx.org.cn",
"iojp.cn",
"jmwlc.cn",
"juyidai.com.cn",
"zlxbw.cn",
"onlinecasinobert.com",
"rfocbc.com",
"kpmsmm.cn",
"allband.com.cn",
"haiyishangpin.com",
"nitline.com",
"pit-magnus.com",
"cajunews.com",
"cakesunlimitedbybenisha.com",
"vsz0709.com.cn",
"herdpride.com",
"ieeenano2012.org",
"28qx.cn",
"szytek.com",
"a9i.net",
"todaysportsnews.net",
"rf168.cn",
"kyntn.com",
"wanda-instr.com.cn",
"ecofriendlyparents.com",
"biomatrixweightloss.com",
"freecnc.org",
"austinstjohn.net",
"hotmegroup.com",
"findingauthenticyou.com",
"hegshows.net",
"losangelesdrumacademy.com",
"pinkribbonsingapore.org",
"eye123.com.cn",
"alofthotelchengdu.cn",
"albrechtai.com",
"realdecorationonline.com",
"bcyeh.cn",
"guilinzipai.cn",
"aiyunyu.com",
"henshuilvyou.com",
"runzhoubj.com",
"saqn.net",
"hamakitacounseling.com",
"0631sdsc.com",
"bt31a.com",
"scrcivf.org",
"zhaishuan.com",
"bjzhydweixiu.com",
"tjhuabang.com",
"lzzsgc.com",
"rztkb.com",
"bynd1999.com",
"oksmt.com",
"bjlh4sd.com",
"hylqgc.com",
"szcailan.com",
"talamuge.com",
"l-zhen.com",
"txkjw.com",
"ziweish.com",
"fdxdj.com",
"mcsysc.com",
"700show.com",
"0731whg.com",
"qbxbkt.com",
"gps288.com",
"yanghuayi.com",
"zerocarbongreen.com",
"wajicanyin.cn",
"anzytech.cn",
"mctanh.cn",
"sstcluck.cn",
"brandzw.cn",
"superdreamers.cn",
"goldboxfx.cn",
"moromoro.cn",
"bzjingyu.cn",
"xjmifengjian.cn",
"jjjvhp.cn",
"syqwii.cn",
"usbhpq.cn",
"mqjbfos.cn",
"cmsscn.cn",
"newsunland.cn",
"shyuewang.cn",
"zevppsx.cn",
"lidqsxb.cn",
"sxydhpt.cn",
"qijinkeji.cn",
"qizhiyd.cn",
"zhidaoit.cn",
"chenghand.cn",
"hnkanke.cn",
"jshmhj.cn",
"lduan.cn",
"lieshouzb.cn",
"qidais.cn",
"adstock.cn",
"dashengzhaoche.cn",
"jiyunxinxuan.cn",
"zikaohunan.cn",
"ztwgsc.cn",
"block88.cn",
"huibaifortune.cn",
"rmtbsw.cn",
"sqxianlingju.cn",
"pbdsw.cn",
"mfbmw.cn",
"gswbw.cn",
"gqxtw.cn",
"glzzw.cn",
"xdcyw.cn",
"xbtmw.cn",
"sxhfw.cn",
"qyfyw.cn",
"wyljw.cn",
"sxdsw.cn",
"mdjcw.cn",
"lxmxw.cn",
"qrwxw.cn",
"mbdrw.cn",
"grjbw.cn",
"syfww.cn",
"qylnw.cn",
"tdxdw.cn",
"lzxpw.cn",
"drcfw.cn",
"dmlpw.cn",
"dppkw.cn",
"dmgfw.cn",
"bjftw.cn",
"eyfdry.cn",
"czxindu.cn",
"lzkeying.cn",
"kipcdh.cn",
"yilantou.cn",
"jlspsy.cn",
"lbjlmm.cn",
"xclhqc.cn",
"cysjgy.cn",
"hbxqg.cn",
"rzmwl.cn",
"jsctdjk.cn",
"sdwecan.cn",
"sxxqg.cn",
"lki8.cn",
"sdppib.cn",
"pmspay.cn",
"iyoutop.cn",
"mxangle.cn",
"0359m.cn",
"0953wk.cn",
"10mmall.cn",
"20p5yy.cn",
"4j77nu.cn",
"4u6l9d.cn",
"5jidh.cn",
"898jk.cn",
"523app.cn",
"yuanmengcai.cn",
"zemaibio.cn",
"zhengpindaigou.cn",
"zhengpinhaitao.cn",
"zhulinxianzi.cn",
"zhyjxc.cn",
"zimi996.cn",
"naozhouou.cn",
"daqianbin.cn",
"pdsddyy.cn",
"xdzby.cn",
"jyshyjxx.cn",
"bingyushangmao.cn",
"easycuresc.cn",
"zhouwuzhengwang.cn",
"jjbls.cn",
"shangyangjishu.cn",
"shandongwantong.cn",
"shanghaigexin.cn",
"xiangtuziwei.cn",
"dongnizhenxuan.cn",
"tongbeim.cn",
"chicllc.cn",
"bleevv.cn",
"temposz.cn",
"dblube.cn",
"boyujianzhi.cn",
"hlwwr.cn",
"dtqys.cn",
"lqkbx.cn",
"ryyhgxp.cn",
"bsgtmrz.cn",
"fshgzj.cn",
"vyvpvf.cn",
"hfqichen.cn",
"qdzhenxin.cn",
"yanxiaowoyzj.cn",
"dingzzong.cn",
"ichiw.cn",
"holck.cn",
"paryoung.cn",
"bjblucci.cn",
"fahub.cn",
"hoyaaa.cn",
"hshcypt.cn",
"hnrbw.cn",
"cygn.cn",
"gxwdcm.com",
"qzkehu.com",
"wlyqw.com",
"xzqbw.com",
"hwzzgc.com",
"dingjunshanfilm.com",
"qdqnw.com",
"ksdrw.com",
"tzyhsz.com",
"convenientcsrds.com",
"nerkommermanalltid.com",
"thefreshconcept.com",
"fkwtq.com",
"bqbxgs.cn",
"cetdk.com",
"lekumi.com",
"zmtlive.com",
"qinansy.com",
"cztbcable.com",
"jiaohuanshuizhi.com",
"sxgygjl.com",
"whappy.cn",
"jhptcn.com",
"qdddmnk.com",
"xintaibaobao.com",
"tianci-rsh.com",
"gzkeway.cn",
"dlxcjc.cn",
"senzha.com",
"vandrere.com",
"mignor.com",
"junei.cn",
"rouchen.cn",
"haolidan.cn",
"hnchtz.com",
"sunmoodhardware.com",
"qdhulan.cn",
"lycymr.cn",
"rayong.cn",
"mnmegagames.com",
"inthebluesky.com",
"htsgh5.com",
"jiangxinsheying.com",
"pzecoin.com",
"fjjaw.com",
"gzduoduo.cn",
"vans8.cn",
"qhblock.cn",
"pinshengwangluo.com",
"lianxiandianhua.com",
"qwtp.cn",
"zhongshankangxi.com",
"sdchuangzhuo.cn",
"lanjingzhuanzhu.com",
"natureasia.cn",
"jsromantic.cn",
"fuxinyusongrong.com",
"wukongtongcheng.com",
"szliantongxiang.com",
"zjzbxf.cn",
"nuoyangshangmao.com",
"jingyanshenghuo.com",
"guoranxiansheng.com",
"jdzyuyao.cn",
"mikl-bd.com",
"valn.com.cn",
"16mnwfgangguan.com",
"shanxizhongjian.com",
"zhongjinguokong.com",
"jadacakes.com",
"evfswim.com",
"talegong.com",
"yqgmbc.com",
"63dxs.com",
"5b188.com",
"954u0.com",
"je273.com",
"se7272.com",
"babehero.com",
"comotres.com",
"87120943.com",
"shiguangcaotang.com",
"eytrz.com",
"wzkangyong.com",
"yimaiwlkj.com",
"shicai22.com",
"jkdofcw.vip",
"hongyunlianlian.com",
"theapkworld.com",
"xiantesenjiaoyu.com",
"erp-jd.com",
"lelejiangyingyu.com",
"guoqiangbaiyuan.com",
"shxyzx.cn",
"zhekouqingbaoju.com",
"lingxixiansheng.com",
"ccnebattery.com",
"czyhchaichu.com",
"kqxn.cn",
"wakaka168.com",
"fjxpel.com",
"mohuyoupin.com",
"caunang.net",
"barrickdownload.com",
"zhangxinhuanbao.com",
"mondashaircare.net",
"saratoganyweddings.com",
"tristatedecksonline.com",
"insideandoutinspection.com",
"sealimousines.com",
"shadyrestcottages.com",
"tennesseewebdeveloper.com",
"sortirencorse.com",
"garrattsonline.com",
"ihateinterviewing.com",
"breenswholesalelumber.com",
"hotelalpiolet.com",
"carolmanochio.com",
"spareroomcandleco.com",
"countyautopartsinc.com",
"speedwayinstruments.com",
"ashleeridingcentre.com",
"lzxp.com.cn",
"yunlingmingyuan.com",
"shengdingjituan.com",
"idreamskyvalley.com",
"happytimellc.net",
"flameking.net",
"shanghaimenghan.com",
"bjanwy.net",
"aoks.net",
"shenyangjinding.com",
"sanmenxianingbo.com",
"za-patitos.com",
"baobaolele.com",
"yxfuke120.com",
"fskjq.com.cn",
"jinzixunedu.com",
"xiangyingzhan.net",
"shenqu.net",
"huiyanxs.com",
"forcewebdesigns.com",
"davidjimproctor.com",
"139nt.net",
"uhyyxy.net",
"gzjimingwlkj.com",
"langley-thai-restaurant.com",
"3ets.com.cn",
"q-sport.com.cn",
"xiaoxiang888.com",
"job0724.cn",
"s-pace1007.com",
"pipz.net",
"truyubeautystudio.com",
"fantabulousbali.com",
"sparkyouththeatre.com",
"vistraprune.com",
"cindy-ellen.com",
"mybighappyfamily.com",
"onedollarfollowers.com",
"soundofclouds.com",
"cankersoreclear.com",
"stevemccomb.com",
"duramtinewfs.com",
"mqdsecurity.com",
"lalbabigfish.com",
"v12sale.com",
"studenti-tu.com",
"thyroid-tips.com",
"brushfirefighter.com",
"in-my-minds-eye.com",
"thriftychristy.com",
"donna-towers.com",
"blogdobraulio.com",
"keeponrepeat.com",
"mtcreasey.com",
"seanmaxwellproject.com",
"waynesworldstage.com",
"guitarburn.com",
"stock-trading-guru.com",
"internet-marketing-by-dda.com",
"osakafu-isoren.com",
"dozikapanasian.com",
"loto-club.com",
"hdicamp.cn",
"hongyeart.cn",
"yunjishuwu.com",
"qizidushu.com",
"costaricagolftours.com",
"judyjamesonline.com",
"crawlerdthdrillingrigs.com",
"w610.com",
"dd8d.com",
"nengzan.cn",
"",]
    for domain in ls:

        d = BaiDu([1,0],kuaizhao_time='0',lang_chinese='1',min_gan_word='0')
        data1 = d.get_info(domain)
        result1 = d.check_baidu(data1,domain)
        print(domain,result1)
        print('=='*10)


    # data = d.get_info('nihao.com')
    # result = d.check_baidu(data,'nihao.com')
    # print(result)
    # data2 = d.get_info('baidu.com')
    # result2 = d.check_baidu(data2, 'baidu.com')
    # print(result2)
